### ISSUE TITLE
Header cells on moves are being scraped and added to the database

### ISSUE THREAD

**Issue by Frannsoft** [Frannsoft/FrannHammer#234]
Fixed this in the old version while seeding data.  Forgot to sanitize results in the new version...

- [x] Sanitize values to keep out header cells
- [x] Write test that verifies these aren't scraped
- [x] Reseed database with newly sanitized rows

**Comment by Frannsoft** [comment]
Fix:

https://github.com/Frannsoft/FrannHammer/commit/9cc3e8726d6537de3611e5defe8f5b7e1d65ea60

**Comment by Frannsoft** [comment]
https://github.com/Frannsoft/FrannHammer/pull/236 - pulled into `develop`

**Comment by rubendal** [comment]
Fixed on all characters except those who have unique properties tables. Cloud, Little Mac, Lucario, Olimar, Peach, Robin, Rosalina, Wii Fit Trainer and Yoshi still have header cells on moves
