### ISSUE TITLE
Some characters have missing characterAttributes

### ISSUE THREAD

**Issue by rubendal** [Frannsoft/FrannHammer#245]
Most characters that have a space in their names have incomplete characterAttributes listed, for example Dark Pit, Captain Falcon and Diddy Kong only have 3 attributes listed: Air Deceleration, Air Friction and Dash Length

Other characters have additional ones, for example Dr. Mario has those 3 and Short Hop listed

**Comment by Frannsoft** [comment]
When attribute data is scraped the character's url safe name is used as a lookup (e.g., 'DarkPit' is used instead of 'Dark Pit'). 

The reason the three attributes listed above are scraped is because they fall into the category of 'everyone else' as listed on the KH site.

**Comment by Frannsoft** [comment]
Fix in https://github.com/Frannsoft/FrannHammer/pull/246

**Comment by Frannsoft** [comment]
- [x]  reseed database

**Comment by Frannsoft** [comment]
Found another issue and fixed it - https://github.com/Frannsoft/FrannHammer/commit/b189ea72a413aef0cd124107c1c72e8f5be1a65c
