### ISSUE TITLE
Missing characterAttributes

### ISSUE THREAD

**Issue by rubendal** [Frannsoft/FrannHammer#248]
Some characterAttributes are missing on the API (most notably Run Speed and Weight), probably not being scraped or having issues on the process

List of missing attributes (based on the KH attributes page):
- Run speed
- Weight
- Reflectors
- Rolls
- Shield size
- Getup options (stand, rolls, jab lock)
- Ledge options (attack, getup, roll, jump), ledge jump here has intangibility and FAF, the ledge hop one that is already on the API only has height
- Trip
- Techs

**Comment by Frannsoft** [comment]
- [x] Run Speed
- [x] Rolls
- [x] Shield size

https://github.com/Frannsoft/FrannHammer/commit/35b9ac816375b02f6eb7726b67d935682af4d500

**Comment by Frannsoft** [comment]
- [x] Reflectors

https://github.com/Frannsoft/FrannHammer/commit/8145a2d30417173c5b73770ddd2b3e1478404f15

**Comment by Frannsoft** [comment]
* [x] Weight

https://github.com/Frannsoft/FrannHammer/commit/eabd24da9a357744f8dc5f8c74f6947d2d977da9

**Comment by Frannsoft** [comment]
* [x] - Trips 
* [x] - GetUp Stand
https://github.com/Frannsoft/FrannHammer/commit/769d85d92ab23d4a79e60cf94e1fc8dd93e5d36a

**Comment by Frannsoft** [comment]
* [x] - Tech
* [x] - rest of GetUp
* [x] - Ledge options
* [x] - Jab lock

https://github.com/Frannsoft/FrannHammer/commit/89f6c63b5ec73052cddede7d13e286f1ad5eb99a
