### ISSUE TITLE
DK's Cargo throws are duplicated

### ISSUE THREAD

**Issue by rubendal** [Frannsoft/FrannHammer#254]

**Comment by Frannsoft** [comment]
Is there a specific api call showing this?  Querying the moves collection in the db directly shows no duplication.

**Comment by rubendal** [comment]
/api/characters/name/{name}/moves, /api/characters/{id}/moves and /api/moves

The ones that are duplicated also have MoveType = ground and have wrong data, for example base damage has angle value

**Comment by Frannsoft** [comment]
Should be fixed in - https://github.com/Frannsoft/FrannHammer/commit/d91789278b643df89226476f3472afdc73dd6a01
