### ISSUE TITLE
Not really an issue: but How can I contribute to the Ultimate Frame Data?

### ISSUE THREAD

**Issue by mxiia** [Frannsoft/FrannHammer#288]
I'd like to try to help finish up parts of the frame data on ultimate (and melee)

**Comment by Frannsoft** [comment]
Hi! Assuming you mean adding the actual frame data I'd reach out to @KuroganeHammer on twitter and ask how you could help out.

If you're referring to this API specifically I can point you to an open issue.

**Comment by Frannsoft** [comment]
I should add that this API does not actually contain the frame data, it pulls it (with permission) off the existing KH site.

**Comment by mxiia** [comment]
Thank you. I assumed this project was directly associated with KH from it being linked on the website
