### ISSUE TITLE
Missing damage values for moves with different damage on ground/air only hitboxes

### ISSUE THREAD

**Issue by rubendal** [Frannsoft/FrannHammer#292]
Move normal base damage data isn't extracted correctly from the site when it has ground/air only hitboxes

Example:

Fox Utilt
![image](https://user-images.githubusercontent.com/10661132/61191143-3d802d80-a66c-11e9-98cd-52baf0854bb9.png)

![image](https://user-images.githubusercontent.com/10661132/61191225-53422280-a66d-11e9-9dc5-654c72af8ff3.png)

Fox Utilt (Late) and Ryu/Ken Dair also have this issue

**Comment by Frannsoft** [comment]
@rubendal I just pushed a potential fix for this in https://github.com/Frannsoft/FrannHammer/commit/e219fb417967dc4630f1dbb4ab6be52db7c18746 and https://github.com/Frannsoft/FrannHammer/commit/f7692326ea1e849ea149921d04a011063198c3d7. Let me know if you still see the issue.

Nice catch!

**Comment by rubendal** [comment]
Moves affected by the issue are now displaying normal base damage correctly

Thanks!
