### ISSUE TITLE
Update Piranha Plant and Banjo & Kazooie URLs to be consistent with other fighters

### ISSUE THREAD

**Issue by dunnaaron** [Frannsoft/FrannHammer#294]
**Examples**

**Piranha Plant** is escaped to "Piranha%20Plant" in all URLs. To be consistent with other fighters, it should be escaped to "PiranhaPlant". 

**Banjo & Kazooie** is escaped to "Banjo-Kazooie" in all URLs. To be consistent with other fighters, it should be escaped to "BanjoKazooie".

**Comment by Frannsoft** [comment]
Hello!

Thanks for pointing this out! I've pushed a change to accommodate this and it's now live. Let me know if you still see the issue.

https://github.com/Frannsoft/FrannHammer/commit/b9b467c5007cf82f65cc0307b530e55f9e7843f7

For anyone seeing this in the future, this is a small (but worthwhile imho) breaking change if you were referencing resource URLs directly for Piranha Plant.

**Comment by dunnaaron** [comment]
Thanks for taking a look at this so quickly. For some reason the thumbnailUrl is now coming back empty, any ideas @Frannsoft ?

**Comment by Frannsoft** [comment]
@dunnaaron  Found the `thumbnailUrl` bug. Should have a fix pushed early tomorrow. Thanks for letting me know!
