### ISSUE TITLE
Ultimate endpoint seems to be broken 

### ISSUE THREAD

**Issue by PaulEunKim** [Frannsoft/FrannHammer#298]
smash4 endpoint works but when game=ultimate, 
{"Message":"Resource of type 'ICharacter' not found."}

**Comment by Frannsoft** [comment]
Hello! Are you seeing this when requesting info for a specific Character?

**Comment by PaulEunKim** [comment]
Yeah, so I tried
`curl https://api.kuroganehammer.com/api/characters/name/ganondorf?game=ultimate`
but `curl https://api.kuroganehammer.com/api/characters/name/ganondorf` works perfectly fine for S4.
I'm looking for the Ultimate data. Thanks in advance!

**Comment by Frannsoft** [comment]
Hmm, so I hit both of those endpoints and I get data back (including using curl). Is it possible you had a typo in your original request? Looking through logs I don't see any 404s associated with calls to ganondorf.

**Comment by Frannsoft** [comment]
Hi @PaulEunKim, are you still seeing an issue on your side regarding this?

**Comment by PaulEunKim** [comment]
Forgot quotes on curl request hehe. Thanks for the speedy responses!
