### ISSUE TITLE
Image Thumbnail URLs are HTTP

### ISSUE THREAD

**Issue by dunnaaron** [Frannsoft/FrannHammer#301]
The thumbnail URLs for the fighters are HTTP and not HTTPS, which can cause insecure content warnings. There may be a discussion that needs to involve KH.

**Comment by Frannsoft** [comment]
Spoke with the KH site owner and site should support https now.

**Comment by Frannsoft** [comment]
This change should be live now. Thanks for letting me know!

**Comment by dunnaaron** [comment]
Confirmed, it is live. Thanks for the quick fix!
