### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by SylveonDeko** [Frannsoft/FrannHammer#306]

**Comment by Frannsoft** [comment]
Hey there! 

I don't really have any plans to update anymore. I think most of the community has moved on at this point to other solutions for getting this type of data.

It's still out there in production and has a few users, but the source of data it pulled from (KuroganeHammer's website) hasn't been updated in quite some time.

Best,
Jordan

**Comment by SylveonDeko** [comment]
Ah yikes
