### ISSUE TITLE
Getting data for throws, rolls, or dodges results in some incorrect or misplaced values

### ISSUE THREAD

**Issue by Sandfall** [Frannsoft/FrannHammer#42]
Throws and Rolls/Dodges are in the same table as ground moves, which causes a couple issues

When you access Throws via the api, the “Weight Dependent?” value and “Base Dmg.” value are found in the “Hitbox Active” and “FAF attributes (respectively). Dodges also have their “intangibility” value under “Hitbox Active”

Apart from it not being all that user friendly, it also causes issues with the values for multi-hit throws. Since FAF is an int (rather than a string), values such as “3, 8” (in Shulk’s FThrow data) show up as 0.

**Comment by Frannsoft** [comment]
Hey @Sandfall ,

Thanks for the Issues and feedback.

I've broken them out into #43 and #44 .

#44 will hopefully be in this next release [see milestone 0.2.0](https://github.com/Frannsoft/FrannHammer/milestones/v0.2.0)

#43 is part of a larger change which can be seen in #31

**Comment by Frannsoft** [comment]
This will be live when milestone v0.2.0 is completed (and changes merged into master):

https://github.com/Frannsoft/FrannHammer/milestones/v0.2.0
